spring:
  application:
    name: portal_cm
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portal_cm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    check-template-location: false

app:
  jwt:
    secret: ${JWT_SECRET:OYyYjiO3CGghpwYZpNEvkSXxB9o6D0wd8q82OsjUwaY1crX6zdlIjYQsbvu71yIn}
    expiration: 28800000  # 8 horas, em milissegundos
  security:
    cookie-secure: false  # true quando rodar em HTTPS
